export const words = {
    headerTitle: "Shopping Cart",
    footerTitle: "© CopyRight Tarek 2022",
    cartHeader: "There is products in cart:",
    content: "There is no content",
    cartTitle: "Title",
    cartQty: "qty",
    cartPrice: "price",
    removeBtn: "Remove",
    selectProducts: "select products",
    total: "Total",
    checkout: "Checkout",
    name: "Name",
    email: "Email",
};